FACTOR_KM_AUTO_GAS = 0.205
FACTOR_KM_AUTO_DIE = 0.177
FACTOR_KM_AUTO_ELEC = 0.067
FACTOR_KM_AUTO_GNC = 0.129
FACTOR_KM_MOTO_GAS = 0.114
FACTOR_KM_CAMION_LIVIANO_DIE = 0.484
FACTOR_KM_COLECT_GAS = 0.107
FACTOR_KM_COLECT_DIE = 0.089
#FACTOR_KM_TREN_ELECT = 0.017
#FACTOR_KM_SUBTE = 0.011

FACTORES = [FACTOR_KM_AUTO_GAS,
            FACTOR_KM_AUTO_DIE,
            FACTOR_KM_AUTO_ELEC,
            FACTOR_KM_AUTO_GNC,
            FACTOR_KM_MOTO_GAS,
            FACTOR_KM_CAMION_LIVIANO_DIE,
            FACTOR_KM_COLECT_GAS,
            FACTOR_KM_COLECT_DIE]